import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import http from "node:http";
import path from "node:path";
import puppeteer from "puppeteer-core";
import { P3_SEED, P3_STORED, installSeed, sleep } from "./economy-moments.mjs";
const DIST = path.join(process.cwd(), "dist");
const MIME = { ".html":"text/html", ".js":"text/javascript", ".css":"text/css", ".json":"application/json", ".svg":"image/svg+xml", ".png":"image/png" };
const server = http.createServer(async (req,res)=>{ const p=decodeURIComponent(req.url.split("?")[0]); let f=path.join(DIST,p); if(!existsSync(f)||p==="/") f=path.join(DIST,"index.html"); try{const b=await readFile(f); res.writeHead(200,{"content-type":MIME[path.extname(f)]??"application/octet-stream"}); res.end(b);}catch{res.writeHead(404);res.end();} });
await new Promise(r=>server.listen(0,r));
const origin = `http://localhost:${server.address().port}`;
const chrome = ["C:/Program Files/Google/Chrome/Application/chrome.exe","C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe","C:/Program Files/Microsoft/Edge/Application/msedge.exe"].find(existsSync);
const browser = await puppeteer.launch({ executablePath: chrome, headless: "new", args:["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({width:390,height:844,deviceScaleFactor:2});
await installSeed(page, origin+"/", P3_SEED, P3_STORED);
await page.goto(`${origin}/#/pathway`, {waitUntil:"networkidle0"});
await sleep(1400);
await page.click(".path-node--current");
await sleep(600);
await page.mouse.move(5, 300);
await sleep(200);
await page.screenshot({path: path.join(process.cwd(),"measurements","_shots","r3-sheet-view.png")});
await page.click(".ns-menu");
await sleep(500);
await page.mouse.move(5, 300);
await sleep(400);
await page.screenshot({path: path.join(process.cwd(),"measurements","_shots","r3-gb-view.png")});
console.log(JSON.stringify(await page.evaluate(()=>{
  const r=(s)=>{const e=document.querySelector(s); if(!e) return null; const b=e.getBoundingClientRect(); return {x:+b.x.toFixed(1),y:+b.y.toFixed(1),w:+b.width.toFixed(1),h:+b.height.toFixed(1)};};
  return {page:r(".gb-page"), head:r(".gb-head"), badge:r(".gb-badge"), intro:r(".gb-intro"), figrow:r(".gb-figrow"), figure:r(".gb-figure"), callout:r(".gb-callout"), strip:r(".gb-strip"), docH: document.querySelector(".gb-overlay").scrollHeight};
}),null,1));
await browser.close(); server.close();
